"""Wave 2 acceptance tests — Direct flow cleanup (Option D).

Validates:
- Direct flow (wallet_flow_direct=True) uses URL button, no WebApp approve surface
- Direct flow pay URL includes flow=direct param
- Direct flow pay URL does NOT include wallet_linked param (no MiniApp connect step)
- Legacy flow (wallet_flow_direct=False) still uses WebApp button (rollback preserved)
- No "Open Braavos" or "Approve & Pay" text generated by bot in direct flow
- Feature flag rollback: toggling to False restores legacy WebApp button
"""

import json
import os
import pytest
from unittest.mock import AsyncMock, MagicMock, patch

# Must be set before importing src modules
os.environ.setdefault("TELEGRAM_BOT_TOKEN", "test-token-000000:AAAAAA")
os.environ.setdefault("WEBHOOK_SECRET", "test-webhook-secret")
os.environ.setdefault("RELAYER_API_URL", "https://api.test.smainer.io")
os.environ.setdefault("RELAYER_API_KEY", "test-relayer-key")
os.environ.setdefault("CALLBACK_SIGNING_SECRET", "test-signing-secret")
os.environ.setdefault("STARKNET_RPC_URL", "https://test-rpc.example.com")
os.environ.setdefault("CALLBACK_BASE_URL", "https://test-bot.vercel.app")

from src.handlers import handle_inference
from src.models import ModelTier
from src.payment import PaymentManager
from src.relayer_client import RelayerClient
from src.wallet import WalletManager

# Patch session operations globally
_session_patch_touch = patch("src.handlers.touch_session", return_value=None)
_session_patch_check = patch("src.handlers.check_session_active", return_value=True)
_session_patch_invalidate = patch("src.handlers.invalidate_session", return_value=None)
_nonce_patch = patch("src.handlers.generate_nonce", return_value="test-nonce-w2")


def setup_module(module):
    _session_patch_touch.start()
    _session_patch_check.start()
    _session_patch_invalidate.start()
    _nonce_patch.start()


def teardown_module(module):
    _session_patch_touch.stop()
    _session_patch_check.stop()
    _session_patch_invalidate.stop()
    _nonce_patch.stop()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_update(text: str, user_id: int = 12345, chat_id: int = 67890):
    return {
        "message": {
            "from": {"id": user_id},
            "chat": {"id": chat_id},
            "text": text,
        }
    }


@pytest.fixture
def mock_bot():
    bot = AsyncMock()
    msg = MagicMock()
    msg.message_id = 999
    bot.send_message.return_value = msg
    bot.edit_message_reply_markup = AsyncMock()
    bot.edit_message_text = AsyncMock()
    bot.send_chat_action = AsyncMock()
    return bot


@pytest.fixture
def deps(mock_bot):
    wallet_mgr = AsyncMock(spec=WalletManager)
    wallet_mgr.get_linked_address.return_value = "0x" + "ab" * 32
    wallet_mgr.has_sufficient_balance.return_value = True

    payment_mgr = AsyncMock(spec=PaymentManager)

    relayer = AsyncMock(spec=RelayerClient)
    relayer.list_available_models.return_value = [
        {"node_id": "n1", "gpu": "RTX4090", "ram_gb": 64, "supported_tiers": ["small"]}
    ]
    relayer.submit_inference.return_value = "task-xyz"
    relayer.kv_get = AsyncMock(return_value=None)
    relayer.kv_set = AsyncMock()

    return {
        "bot": mock_bot,
        "wallet_mgr": wallet_mgr,
        "payment_mgr": payment_mgr,
        "relayer": relayer,
    }


# ---------------------------------------------------------------------------
# Wave 2: Direct flow has no MiniApp approve/open-Braavos surface
# ---------------------------------------------------------------------------


class TestWave2DirectFlowNoApproveUI:
    """User never sees MiniApp approve/open-Braavos UI in the direct flow."""

    @pytest.mark.asyncio
    @patch("src.handlers.settings")
    async def test_direct_flow_url_contains_flow_direct(self, mock_settings, deps):
        """Direct flow pay URL must contain flow=direct to trigger auto-redirect."""
        mock_settings.wallet_flow_direct = True
        mock_settings.default_model = "llama3.1:8b"
        mock_settings.prompt_cost_strk = 100_000_000_000_000_000
        mock_settings.miniapp_url = "https://smainer-miniapp.vercel.app"
        mock_settings.get_direct_pay_url.return_value = (
            "https://smainer-miniapp.vercel.app/?action=pay&flow=direct"
            "&prompt=test&tier=small&chat_id=67890&message_id=999&nonce=test-nonce-w2"
        )
        mock_settings.telemetry_sensitive_fields = False

        update = _make_update("Test compute task")
        await handle_inference(
            update,
            deps["bot"],
            deps["wallet_mgr"],
            deps["payment_mgr"],
            deps["relayer"],
        )

        deps["bot"].edit_message_reply_markup.assert_called_once()
        call_kwargs = deps["bot"].edit_message_reply_markup.call_args[1]
        keyboard = call_kwargs["reply_markup"]
        button = keyboard.inline_keyboard[0][0]

        # Must be a URL button, not WebApp
        assert button.url is not None, "Direct flow must use URL button"
        assert button.web_app is None, "Direct flow must NOT use WebApp button"
        assert "flow=direct" in button.url

    @pytest.mark.asyncio
    @patch("src.handlers.settings")
    async def test_direct_flow_url_has_no_wallet_linked_param(self, mock_settings, deps):
        """Direct flow URL must NOT include wallet_linked — no MiniApp connect step."""
        mock_settings.wallet_flow_direct = True
        mock_settings.default_model = "llama3.1:8b"
        mock_settings.prompt_cost_strk = 100_000_000_000_000_000
        mock_settings.miniapp_url = "https://smainer-miniapp.vercel.app"
        mock_settings.get_direct_pay_url.return_value = (
            "https://smainer-miniapp.vercel.app/?action=pay&flow=direct"
            "&prompt=test&tier=small&chat_id=67890&message_id=999"
        )
        mock_settings.telemetry_sensitive_fields = False

        update = _make_update("Another test")
        await handle_inference(
            update,
            deps["bot"],
            deps["wallet_mgr"],
            deps["payment_mgr"],
            deps["relayer"],
        )

        button = deps["bot"].edit_message_reply_markup.call_args[1]["reply_markup"].inline_keyboard[0][0]
        assert "wallet_linked" not in button.url, "Direct flow must not reference wallet_linked"

    @pytest.mark.asyncio
    @patch("src.handlers.settings")
    async def test_direct_flow_bot_message_no_approve_text(self, mock_settings, deps):
        """Bot message text must not mention 'approve' or 'Open Braavos' in direct flow."""
        mock_settings.wallet_flow_direct = True
        mock_settings.default_model = "llama3.1:8b"
        mock_settings.prompt_cost_strk = 100_000_000_000_000_000
        mock_settings.miniapp_url = "https://smainer-miniapp.vercel.app"
        mock_settings.get_direct_pay_url.return_value = (
            "https://smainer-miniapp.vercel.app/?action=pay&flow=direct&prompt=hi"
        )
        mock_settings.telemetry_sensitive_fields = False

        update = _make_update("Hello AI")
        await handle_inference(
            update,
            deps["bot"],
            deps["wallet_mgr"],
            deps["payment_mgr"],
            deps["relayer"],
        )

        # Check all send_message calls
        for call in deps["bot"].send_message.call_args_list:
            text = call[1].get("text", "")
            text_lower = text.lower()
            assert "open braavos" not in text_lower, f"Bot must not mention 'Open Braavos': {text}"
            assert "approve & pay" not in text_lower, f"Bot must not mention 'Approve & Pay': {text}"

    @pytest.mark.asyncio
    @patch("src.handlers.settings")
    async def test_direct_flow_button_text_is_pay_and_compute(self, mock_settings, deps):
        """Direct flow button must be '💎 Pay & Compute', not 'Approve & Pay'."""
        mock_settings.wallet_flow_direct = True
        mock_settings.default_model = "llama3.1:8b"
        mock_settings.prompt_cost_strk = 100_000_000_000_000_000
        mock_settings.miniapp_url = "https://smainer-miniapp.vercel.app"
        mock_settings.get_direct_pay_url.return_value = (
            "https://smainer-miniapp.vercel.app/?action=pay&flow=direct&prompt=hi"
        )
        mock_settings.telemetry_sensitive_fields = False

        update = _make_update("Test prompt")
        await handle_inference(
            update,
            deps["bot"],
            deps["wallet_mgr"],
            deps["payment_mgr"],
            deps["relayer"],
        )

        button = deps["bot"].edit_message_reply_markup.call_args[1]["reply_markup"].inline_keyboard[0][0]
        assert button.text == "💎 Pay & Compute", f"Button text should be 'Pay & Compute', got: {button.text}"
        assert "approve" not in button.text.lower()
        assert "braavos" not in button.text.lower()


# ---------------------------------------------------------------------------
# Rollback: Legacy flow still works with feature flag off
# ---------------------------------------------------------------------------


class TestWave2LegacyRollbackPreserved:
    """Toggling wallet_flow_direct=False restores legacy WebApp flow."""

    @pytest.mark.asyncio
    @patch("src.handlers.settings")
    async def test_legacy_flow_uses_webapp_button(self, mock_settings, deps):
        """When wallet_flow_direct=False, bot uses WebApp button."""
        mock_settings.wallet_flow_direct = False
        mock_settings.default_model = "llama3.1:8b"
        mock_settings.prompt_cost_strk = 100_000_000_000_000_000
        mock_settings.miniapp_url = "https://smainer-miniapp.vercel.app"
        mock_settings.get_miniapp_pay_url.return_value = (
            "https://smainer-miniapp.vercel.app/?action=pay&prompt=hi"
        )
        mock_settings.telemetry_sensitive_fields = False

        update = _make_update("Legacy test prompt")
        await handle_inference(
            update,
            deps["bot"],
            deps["wallet_mgr"],
            deps["payment_mgr"],
            deps["relayer"],
        )

        button = deps["bot"].edit_message_reply_markup.call_args[1]["reply_markup"].inline_keyboard[0][0]
        assert button.web_app is not None, "Legacy flow must use WebApp button"
        assert button.url is None, "Legacy flow must NOT use URL button"

    @pytest.mark.asyncio
    @patch("src.handlers.settings")
    async def test_feature_flag_toggle_direct_then_legacy(self, mock_settings, deps):
        """Toggle from direct to legacy restores WebApp button — no residual."""
        # Direct flow first
        mock_settings.wallet_flow_direct = True
        mock_settings.default_model = "llama3.1:8b"
        mock_settings.prompt_cost_strk = 100_000_000_000_000_000
        mock_settings.miniapp_url = "https://smainer-miniapp.vercel.app"
        mock_settings.get_direct_pay_url.return_value = "https://smainer-miniapp.vercel.app/?flow=direct"
        mock_settings.get_miniapp_pay_url.return_value = "https://smainer-miniapp.vercel.app/?action=pay"
        mock_settings.telemetry_sensitive_fields = False

        update = _make_update("Toggle test")
        await handle_inference(
            update,
            deps["bot"],
            deps["wallet_mgr"],
            deps["payment_mgr"],
            deps["relayer"],
        )

        button1 = deps["bot"].edit_message_reply_markup.call_args[1]["reply_markup"].inline_keyboard[0][0]
        assert button1.url is not None, "First call should be URL (direct)"

        # Reset mock and switch to legacy
        deps["bot"].reset_mock()
        msg = MagicMock()
        msg.message_id = 1001
        deps["bot"].send_message.return_value = msg
        mock_settings.wallet_flow_direct = False

        await handle_inference(
            update,
            deps["bot"],
            deps["wallet_mgr"],
            deps["payment_mgr"],
            deps["relayer"],
        )

        button2 = deps["bot"].edit_message_reply_markup.call_args[1]["reply_markup"].inline_keyboard[0][0]
        assert button2.web_app is not None, "Second call should be WebApp (legacy rollback)"
        assert button2.url is None


# ---------------------------------------------------------------------------
# Wave 2: No wallet_linked in get_direct_pay_url (config-level guarantee)
# ---------------------------------------------------------------------------


class TestWave2ConfigDirectPayUrl:
    """get_direct_pay_url must never include wallet_linked param."""

    def test_get_direct_pay_url_no_wallet_linked(self):
        """Config method produces clean URL with flow=direct, no wallet_linked."""
        from src.config import Settings

        s = Settings(
            telegram_bot_token="test-tok:AAAA",
            miniapp_url="https://smainer-miniapp.vercel.app",
        )
        url = s.get_direct_pay_url(
            prompt="hello",
            tier="small",
            chat_id=123,
            message_id=456,
            nonce="nonce-test",
        )
        assert "flow=direct" in url
        assert "wallet_linked" not in url
        assert "action=pay" in url
        assert "nonce=nonce-test" in url
